//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalangSampah.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DalangConn : DbContext
    {
        public DalangConn()
            : base("name=DalangConn")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jabatan> Jabatans { get; set; }
        public virtual DbSet<Karyawan> Karyawans { get; set; }
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Nasabah> Nasabahs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SubKategori> SubKategoris { get; set; }
        public virtual DbSet<TipeIdentita> TipeIdentitas { get; set; }
        public virtual DbSet<Trx> Trxes { get; set; }
        public virtual DbSet<TrxDetail> TrxDetails { get; set; }
        public virtual DbSet<TrxType> TrxTypes { get; set; }
    }
}
