//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalangSampah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karyawan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Karyawan()
        {
            this.Trxes = new HashSet<Trx>();
        }
    
        public int ID { get; set; }
        public int JabatanID { get; set; }
        public int StatusID { get; set; }
        public string NamaDepan { get; set; }
        public string NamaBelakang { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime Dob { get; set; }
        public System.DateTime TglGabung { get; set; }
        public string Alamat { get; set; }
    
        public virtual Jabatan Jabatan { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trx> Trxes { get; set; }
    }
}
