//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalangSampah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrxDetail
    {
        public int ID { get; set; }
        public int TrxID { get; set; }
        public Nullable<int> SubKatID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> Harga { get; set; }
        public Nullable<decimal> Ammount { get; set; }
    
        public virtual SubKategori SubKategori { get; set; }
        public virtual Trx Trx { get; set; }
    }
}
